### PR TITLE
Use the same sourceFile Name when applySourceMap

### PR DESCRIPTION
**Pull request by clempat**
I maybe miss something but this Fix would be related to:
- https://github.com/sindresorhus/gulp-autoprefixer/issues/8
- https://github.com/floridoo/gulp-sourcemaps/issues/60

Can you tell me what do you think ?

### CODE REVIEW

**Comment by clempat** [comment]
I still have other issue...

**Comment by mariusGundersen** [comment]
As mentioned in the original comment this seems to fix the gulp-sass|gulp-autoprefixer|gulp-sourcemaps issue. Why has this not been merged? Does it create other issues?

**Comment by clempat** [comment]
Not as far as I know...

**Comment by mariusGundersen** [comment]
What did you refer to when you said you had an other issue @clempat? Did this create some issue or did it not fix your issue after all?

**Comment by clempat** [comment]
Ah Yes true, shame I don't remember why I said I still had an issue. What I can say now is I was using it on project using gulp and did not get anymore issues as far I remember. And for sure was fixing the issues I mentioned.

**Comment by floridoo** [comment]
Sorry for the late answer. This was not merged because this change seems wrong to me: The second parameter to `SourceMapGenerator.prototype.applySourceMap` is the source file in the generator that the source map in the first parameter should be applied to. In this case that should be `file.sourceMap.file` (= the output file of `file.sourceMap`), not `sourceMap.file` (which is the output file of the source map in the generator).

Can you explain to me why it should be `sourceMap.file`?

**Comment by clempat** [comment]
I would have to check again as it was some time ago. As well that I start now to use npm script. Yeah got into the way grunt->gulp->npm script :)... I could just refer to my comment:
> From my side while debugging I saw that the sourcemap was overwritten because of the source file name different (for my case, first app.scss and then app.css) 

https://github.com/mozilla/source-map/blob/0.4.4/lib/source-map/source-map-generator.js#L194

**Comment by floridoo** [comment]
Thanks @clempat!
Sounds like the `file` or `sources` entry of the passed source maps were incorrect and this change fixed it for that case. But it could break other uses, so I won't merge this.

**Comment by mariusGundersen** [comment]
BTW, this is the cause of this issue too: https://github.com/terinjokes/gulp-uglify/issues/105

**Pull request closed without merging**
